/***************************************************************************
 * The contents of this file were generated with Amplify Studio.           *
 * Please refrain from making any modifications to this file.              *
 * Any changes to this file will be overwritten when running amplify pull. *
 **************************************************************************/

/* eslint-disable */
import * as React from "react";
import { getOverrideProps } from "@aws-amplify/ui-react/internal";
import { Text, View } from "@aws-amplify/ui-react";
export default function Achievement(props) {
  const { overrides, ...rest } = props;
  return (
    <View
      width="1920px"
      height="425px"
      display="block"
      gap="unset"
      alignItems="unset"
      justifyContent="unset"
      position="relative"
      padding="0px 0px 0px 0px"
      {...getOverrideProps(overrides, "Achievement")}
      {...rest}
    >
      <View
        width="1920px"
        height="425px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="0%"
        bottom="0%"
        left="0%"
        right="0%"
        padding="0px 0px 0px 0px"
        backgroundColor="rgba(250,250,250,1)"
        {...getOverrideProps(overrides, "Rectangle 103")}
      ></View>
      <Text
        fontFamily="Raleway"
        fontSize="105px"
        fontWeight="700"
        color="rgba(221,221,221,1)"
        lineHeight="123.27000427246094px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        letterSpacing="-4.05px"
        width="unset"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="28.47%"
        bottom="42.59%"
        left="20.78%"
        right="67.92%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="720+"
        {...getOverrideProps(overrides, "720+")}
      ></Text>
      <Text
        fontFamily="Raleway"
        fontSize="105px"
        fontWeight="700"
        color="rgba(221,221,221,1)"
        lineHeight="123.27000427246094px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        letterSpacing="-4.05px"
        width="unset"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="28.47%"
        bottom="42.59%"
        left="36.41%"
        right="52.19%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="920+"
        {...getOverrideProps(overrides, "920+")}
      ></Text>
      <Text
        fontFamily="Raleway"
        fontSize="105px"
        fontWeight="700"
        color="rgba(221,221,221,1)"
        lineHeight="123.27000427246094px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        letterSpacing="-4.05px"
        width="unset"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="28.47%"
        bottom="42.59%"
        left="53.85%"
        right="38.18%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="25+"
        {...getOverrideProps(overrides, "25+")}
      ></Text>
      <Text
        fontFamily="Raleway"
        fontSize="105px"
        fontWeight="700"
        color="rgba(221,221,221,1)"
        lineHeight="123.27000427246094px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        letterSpacing="-4.05px"
        width="unset"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="28.47%"
        bottom="42.59%"
        left="67.97%"
        right="20.47%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="700+"
        {...getOverrideProps(overrides, "700+")}
      ></Text>
      <Text
        fontFamily="Raleway"
        fontSize="18px"
        fontWeight="600"
        color="rgba(83,83,83,1)"
        lineHeight="21.131999969482422px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        letterSpacing="0.03px"
        width="unset"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="58.82%"
        bottom="36.24%"
        left="21.93%"
        right="69.06%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="Projects Completed"
        {...getOverrideProps(overrides, "Projects Completed")}
      ></Text>
      <Text
        fontFamily="Raleway"
        fontSize="18px"
        fontWeight="600"
        color="rgba(83,83,83,1)"
        lineHeight="21.131999969482422px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        letterSpacing="0.03px"
        width="unset"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="58.82%"
        bottom="36.24%"
        left="38.91%"
        right="54.74%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="Products Sold"
        {...getOverrideProps(overrides, "Products Sold")}
      ></Text>
      <Text
        fontFamily="Raleway"
        fontSize="18px"
        fontWeight="600"
        color="rgba(83,83,83,1)"
        lineHeight="21.131999969482422px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        letterSpacing="0.03px"
        width="unset"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="58.82%"
        bottom="36.24%"
        left="53.91%"
        right="38.23%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="Awards Received"
        {...getOverrideProps(overrides, "Awards Received")}
      ></Text>
      <Text
        fontFamily="Raleway"
        fontSize="18px"
        fontWeight="600"
        color="rgba(83,83,83,1)"
        lineHeight="21.131999969482422px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        letterSpacing="0.03px"
        width="unset"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="58.82%"
        bottom="36.24%"
        left="70.57%"
        right="23.13%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="Happy Clients"
        {...getOverrideProps(overrides, "Happy Clients")}
      ></Text>
    </View>
  );
}
