/***************************************************************************
 * The contents of this file were generated with Amplify Studio.           *
 * Please refrain from making any modifications to this file.              *
 * Any changes to this file will be overwritten when running amplify pull. *
 **************************************************************************/

/* eslint-disable */
import * as React from "react";
import { getOverrideProps } from "@aws-amplify/ui-react/internal";
import { Image, Text, View } from "@aws-amplify/ui-react";
export default function Offerings(props) {
  const { overrides, ...rest } = props;
  return (
    <View
      width="1534px"
      height="583px"
      display="block"
      gap="unset"
      alignItems="unset"
      justifyContent="unset"
      position="relative"
      padding="0px 0px 0px 0px"
      {...getOverrideProps(overrides, "Offerings")}
      {...rest}
    >
      <Text
        fontFamily="Ionicons"
        fontSize="85px"
        fontWeight="500"
        color="rgba(159,159,159,1)"
        lineHeight="92.63671875px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="unset"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="58.32%"
        bottom="25.73%"
        left="96.48%"
        right="0%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children=""
        {...getOverrideProps(overrides, "\uF3D6")}
      ></Text>
      <Text
        fontFamily="Ionicons"
        fontSize="85px"
        fontWeight="500"
        color="rgba(159,159,159,0.31)"
        lineHeight="92.63671875px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="unset"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="58.32%"
        bottom="25.73%"
        left="0%"
        right="96.48%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children=""
        {...getOverrideProps(overrides, "\uF3D5")}
      ></Text>
      <View
        padding="0px 0px 0px 0px"
        width="1270px"
        height="393px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="32.59%"
        bottom="0%"
        left="8.6%"
        right="8.6%"
        {...getOverrideProps(overrides, "1")}
      >
        <View
          width="404px"
          height="392.67px"
          display="block"
          gap="unset"
          alignItems="unset"
          justifyContent="unset"
          position="absolute"
          top="0%"
          bottom="0.08%"
          left="0%"
          right="68.19%"
          boxShadow="0px 2px 40px rgba(0.7333333492279053, 0.7333333492279053, 0.7333333492279053, 0.5)"
          borderRadius="90px"
          padding="0px 0px 0px 0px"
          backgroundColor="rgba(253,253,253,1)"
          {...getOverrideProps(overrides, "Rectangle 73")}
        ></View>
        <View
          width="404px"
          height="392.67px"
          display="block"
          gap="unset"
          alignItems="unset"
          justifyContent="unset"
          position="absolute"
          top="0.08%"
          bottom="0%"
          left="34.09%"
          right="34.09%"
          border="1px SOLID rgba(235,235,235,1)"
          borderRadius="90px"
          padding="0px 0px 0px 0px"
          backgroundColor="rgba(253,253,253,1)"
          {...getOverrideProps(overrides, "Rectangle 74")}
        ></View>
        <View
          width="404px"
          height="392.67px"
          display="block"
          gap="unset"
          alignItems="unset"
          justifyContent="unset"
          position="absolute"
          top="0.08%"
          bottom="0%"
          left="68.19%"
          right="0%"
          border="1px SOLID rgba(235,235,235,1)"
          borderRadius="90px"
          padding="0px 0px 0px 0px"
          backgroundColor="rgba(253,253,253,1)"
          {...getOverrideProps(overrides, "Rectangle 75")}
        ></View>
        <Image
          width="6.54%"
          height="21.16%"
          display="block"
          gap="unset"
          alignItems="unset"
          justifyContent="unset"
          position="absolute"
          top="17.16%"
          bottom="61.68%"
          left="46.69%"
          right="46.77%"
          padding="0px 0px 0px 0px"
          objectFit="cover"
          {...getOverrideProps(overrides, "Shirt Plain")}
        ></Image>
        <Text
          fontFamily="Raleway"
          fontSize="25px"
          fontWeight="600"
          color="rgba(45,45,45,1)"
          lineHeight="29.350000381469727px"
          textAlign="center"
          display="block"
          direction="column"
          justifyContent="unset"
          letterSpacing="0.1px"
          width="199px"
          height="29.05px"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="49.53%"
          bottom="43.08%"
          left="8.11%"
          right="76.22%"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="Branding Design"
          {...getOverrideProps(overrides, "Branding Design")}
        ></Text>
        <Text
          fontFamily="Raleway"
          fontSize="25px"
          fontWeight="600"
          color="rgba(45,45,45,1)"
          lineHeight="29.350000381469727px"
          textAlign="center"
          display="block"
          direction="column"
          justifyContent="unset"
          letterSpacing="0.1px"
          width="171px"
          height="29.05px"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="49.53%"
          bottom="43.08%"
          left="43.31%"
          right="43.23%"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="T-Shirt Design"
          {...getOverrideProps(overrides, "T-Shirt Design")}
        ></Text>
        <Text
          fontFamily="Raleway"
          fontSize="25px"
          fontWeight="600"
          color="rgba(45,45,45,1)"
          lineHeight="29.350000381469727px"
          textAlign="center"
          display="block"
          direction="column"
          justifyContent="unset"
          letterSpacing="0.1px"
          width="193px"
          height="29.05px"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="49.53%"
          bottom="43.08%"
          left="76.54%"
          right="8.27%"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="Package Design"
          {...getOverrideProps(overrides, "Package Design")}
        ></Text>
        <Text
          fontFamily="Lato"
          fontSize="16px"
          fontWeight="400"
          color="rgba(146,146,146,1)"
          lineHeight="28.349061965942383px"
          textAlign="center"
          display="block"
          direction="column"
          justifyContent="unset"
          letterSpacing="0.01px"
          width="310px"
          height="81.14px"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="61%"
          bottom="18.35%"
          left="3.54%"
          right="72.05%"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Orci eget mi elit cursus donec amet sed sagittis."
          {...getOverrideProps(
            overrides,
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Orci eget mi elit cursus donec amet sed sagittis.2187"
          )}
        ></Text>
        <Text
          fontFamily="Lato"
          fontSize="16px"
          fontWeight="400"
          color="rgba(146,146,146,1)"
          lineHeight="28.349061965942383px"
          textAlign="center"
          display="block"
          direction="column"
          justifyContent="unset"
          letterSpacing="0.01px"
          width="310px"
          height="81.14px"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="61%"
          bottom="18.35%"
          left="37.8%"
          right="37.8%"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Orci eget mi elit cursus donec amet sed sagittis."
          {...getOverrideProps(
            overrides,
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Orci eget mi elit cursus donec amet sed sagittis.2188"
          )}
        ></Text>
        <Text
          fontFamily="Lato"
          fontSize="16px"
          fontWeight="400"
          color="rgba(146,146,146,1)"
          lineHeight="28.349061965942383px"
          textAlign="center"
          display="block"
          direction="column"
          justifyContent="unset"
          letterSpacing="0.01px"
          width="310px"
          height="81.14px"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="61%"
          bottom="18.35%"
          left="71.89%"
          right="3.7%"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Orci eget mi elit cursus donec amet sed sagittis."
          {...getOverrideProps(
            overrides,
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Orci eget mi elit cursus donec amet sed sagittis.2189"
          )}
        ></Text>
        <Image
          width="6.54%"
          height="21.16%"
          display="block"
          gap="unset"
          alignItems="unset"
          justifyContent="unset"
          position="absolute"
          top="17.16%"
          bottom="61.68%"
          left="12.44%"
          right="81.02%"
          padding="0px 0px 0px 0px"
          objectFit="cover"
          {...getOverrideProps(overrides, "Rectangle")}
        ></Image>
        <Image
          width="6.54%"
          height="21.16%"
          display="block"
          gap="unset"
          alignItems="unset"
          justifyContent="unset"
          position="absolute"
          top="17.67%"
          bottom="61.17%"
          left="80.79%"
          right="12.68%"
          padding="0px 0px 0px 0px"
          objectFit="cover"
          {...getOverrideProps(overrides, "Shipment Upload")}
        ></Image>
      </View>
      <Text
        fontFamily="Lato"
        fontSize="16px"
        fontWeight="400"
        color="rgba(144,144,144,1)"
        lineHeight="29.62906265258789px"
        textAlign="center"
        display="block"
        direction="column"
        justifyContent="unset"
        letterSpacing="0.17px"
        width="439px"
        height="58px"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="12.18%"
        bottom="77.87%"
        left="35.72%"
        right="35.66%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="Things that I can do for my clients. Just make your good trust I love to provide quality works."
        {...getOverrideProps(
          overrides,
          "Things that I can do for my clients. Just make your good trust I love to provide quality works."
        )}
      ></Text>
      <Text
        fontFamily="Raleway"
        fontSize="48px"
        fontWeight="700"
        color="rgba(45,45,45,1)"
        textTransform="capitalize"
        lineHeight="56.35200119018555px"
        textAlign="center"
        display="block"
        direction="column"
        justifyContent="unset"
        letterSpacing="-0.33px"
        width="272px"
        height="56px"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="0%"
        bottom="90.39%"
        left="41.13%"
        right="41.13%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="What I Offer"
        {...getOverrideProps(overrides, "What I Offer")}
      ></Text>
    </View>
  );
}
