/***************************************************************************
 * The contents of this file were generated with Amplify Studio.           *
 * Please refrain from making any modifications to this file.              *
 * Any changes to this file will be overwritten when running amplify pull. *
 **************************************************************************/

import * as React from "react";
import { EscapeHatchProps } from "@aws-amplify/ui-react/internal";
import { IconProps, TextProps, ViewProps } from "@aws-amplify/ui-react";
export declare type PrimitiveOverrideProps<T> = Partial<T> & React.DOMAttributes<HTMLDivElement>;
export declare type TestimonialsOverridesProps = {
    Testimonials?: PrimitiveOverrideProps<ViewProps>;
    Pattern?: PrimitiveOverrideProps<ViewProps>;
    "Ellipse 202196"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 202197"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 202198"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 202199"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 202200"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 202201"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 202202"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 202203"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 202204"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 202205"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 202206"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 202207"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 202208"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 202209"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 202210"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 202211"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 202212"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 202213"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 202214"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 202215"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 202216"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 202217"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 202218"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 202219"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 202220"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 202221"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 202222"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 202223"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 202224"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 202225"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 202226"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 202227"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 202228"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 202229"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 202230"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 202231"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 202232"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 202233"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 202234"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 202235"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 202236"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 202237"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 202238"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 202239"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 202240"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 202241"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 202242"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 202243"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 202244"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 202245"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 202246"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 202247"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 202248"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 202249"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 202250"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 202251"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 202252"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 202253"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 202254"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 202255"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 202256"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 202257"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 202258"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 202259"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 202260"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 202261"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 202262"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 202263"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 202264"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 202265"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 202266"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 202267"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 202268"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 202269"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 202270"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 202271"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 202272"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 202273"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 202274"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 202275"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 202276"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 202277"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 202278"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 202279"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 202280"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 202281"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 202282"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 202283"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 202284"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 202285"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 202286"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 202287"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 202288"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 202289"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 202290"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 202291"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 202292"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 202293"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 202294"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 202295"?: PrimitiveOverrideProps<IconProps>;
    "CEO - Squirrel Sweets"?: PrimitiveOverrideProps<TextProps>;
    "Emma Brown"?: PrimitiveOverrideProps<TextProps>;
    "Ellipse 19"?: PrimitiveOverrideProps<IconProps>;
    "\uE977"?: PrimitiveOverrideProps<TextProps>;
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Dapibus eu placerat at nisl posuere aliquet amet pharetra malesuada. Suspendisse nisl ac at tortor."?: PrimitiveOverrideProps<TextProps>;
} & EscapeHatchProps;
export declare type TestimonialsProps = React.PropsWithChildren<Partial<ViewProps> & {
    overrides?: TestimonialsOverridesProps | undefined | null;
}>;
export default function Testimonials(props: TestimonialsProps): React.ReactElement;
